### ISSUE TITLE
Error when running validation labels against themselves

### ISSUE THREAD

**Issue by lopuhin** [mapillary/mapillary_vistas#4]
As a sanity check, I ran evaluation script against validation labels (expecting a perfect score) and got the following error:
```
$ python mapillary_vistas/tools/evaluation.py --dataset-config ../mapillary-vistas-2017/data/config.json --ground-truth-labels ..
/mapillary-vistas-2017/data/validation/ --prediction-labels ../mapillary-vistas-2017/data/validation/ -j 16
Parsing directories for images...
Found 4000 predictions with ground truth
Analysing predictions
  0%|                                                                                                                                                   | 0/4000 [00:00<?, ?it/s]
/home/kostia/ml/mapillary_vistas/mapillary_vistas/tools/../../mapillary_vistas/evaluation/evaluation.py:52: RuntimeWarning: You specified 8bit label files as ground truth.
It is not possible to derive instance specific metrics from these images.
Specify the 16bit instance files.
  warnings.warn(warn_text, RuntimeWarning)
...
 50%|███████████████████████████████████████████████████████████████████▋                                                                    | 1992/4000 [01:12<01:20, 25.01it/s]
Traceback (most recent call last):
  File "/home/kostia/ml/mapillary_vistas/mapillary_vistas/tools/../../mapillary_vistas/evaluation/evaluation.py", line 57, in process_image
    assert prediction_array.dtype == np.uint8
AssertionError
problem in processing /home/kostia/ml/mapillary-vistas-2017/data/validation/instances/Uudh-FzQX_6weEQLptf3qQ.png, /home/kostia/ml/mapillary-vistas-2017/data/validation/instances
/Uudh-FzQX_6weEQLptf3qQ.png
Traceback (most recent call last):
  File "mapillary_vistas/tools/evaluation.py", line 132, in <module>
    main()
  File "mapillary_vistas/tools/evaluation.py", line 124, in main
    args,
  File "/home/kostia/ml/mapillary_vistas/mapillary_vistas/tools/../../mapillary_vistas/evaluation/evaluation.py", line 199, in evaluate_dirs
    for result in progress(results, total=len(image_tuples)):
  File "/home/kostia/ml/mapillary_vistas/venv/local/lib/python2.7/site-packages/tqdm/_tqdm.py", line 833, in __iter__
    for obj in iterable:
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 668, in next
Traceback (most recent call last):
  File "/home/kostia/ml/mapillary_vistas/mapillary_vistas/tools/../../mapillary_vistas/evaluation/evaluation.py", line 57, in process_image
    assert prediction_array.dtype == np.uint8
AssertionError
problem in processing /home/kostia/ml/mapillary-vistas-2017/data/validation/instances/VpYToPeA6tTer5n8RB6-Zg.png, /home/kostia/ml/mapillary-vistas-2017/data/validation/instances
/VpYToPeA6tTer5n8RB6-Zg.png
    raise value
AssertionError
```

**Comment by lopuhin** [comment]
image dtype is int32, and it looks greyish, so maybe there is just something wrong with this particular image

**Comment by tobias-o** [comment]
Hi,
Please specify `<MVD root>/validation/instances` or `<MVD root>/validation/labels/` (and not `<MVD root>/validation`) as `--ground-truth-labels` and `--prediction-labels`.
Otherwise you are mixing instance specific and non-instance specific data which is not supported by the script

**Comment by lopuhin** [comment]
@tobias-o ah right, thanks! I was wondering where did 4000 images came from, somehow missed the last part of the path. Now it runs!
